<div style="background-color:#009DD1; padding: 10px; height: 70px; border-radius: 15px;">
    <div style="font-family: 'Georgia', serif; font-size: 20px;color: white; padding: 10px; text-align: right; position: absolute; right: 20px;">
        Sakshi <br>
        <span style="font-family: 'Arial', sans-serif;font-size: 14px; color: white">Data Analytics Trainee|AI/ML bootcamp</span> 
    </div>
</div>

<div style="background-color: #01377D; padding: 10px; text-align: center; color: white; font-size: 32px; font-family: 'Arial', sans-serif;">
    Data Cleaning & Visualization <br><br>
    
</div>

### Data cleaning is the process of fixing or removing incorrect, corrupted, or missing data. It’s a crucial step in the data analysis process to ensure reliable results.

<div style="background-color: #97E7F5; color: white ; padding: 4px;">
    <h3> Why Data Cleaning important
</h3> </div>

<div style="background-color: #97E7F5; color: white ; padding: 4px;">
    <h3> Libraries used:
</h3> </div>

In [1]:
#import libraries

import numpy as np
import pandas as pd

<div style="background-color: #9F149F; color: white ; padding: 4px;">
    <h3> Create data
</h3> </div>

In [2]:
#
data = [
    {"Transaction ID": 1001, "Customer Name": "Alice Smith", "Email": "alice@example.com", "Product": "Laptop", "Quantity": 1, "Price": 1200.00, "Purchase Date": "2024-09-15", "Delivery Status": True},
    {"Transaction ID": 1002, "Customer Name": "Bob Jones", "Email": None, "Product": "Headphones", "Quantity": 2, "Price": 150.00, "Purchase Date": "2024-09-16", "Delivery Status": True},
    {"Transaction ID": 1003, "Customer Name": "Charlie Johnson", "Email": "charlie#example.com", "Product": "Smartphone", "Quantity": 1, "Price": 800.00, "Purchase Date": "16/09/2024", "Delivery Status": True},
    {"Transaction ID": 1004, "Customer Name": "David Lee", "Email": "david.lee@example.com", "Product": "Laptop", "Quantity": 1, "Price": 1200.00, "Purchase Date": "2024-09-17", "Delivery Status": False},
    {"Transaction ID": 1005, "Customer Name": "Eve Martinez", "Email": "eve.martinez@example.com", "Product": "Smartwatch", "Quantity": 3, "Price": None, "Purchase Date": "17th Sep 2024", "Delivery Status": True},
    {"Transaction ID": 1006, "Customer Name": "Frank Wright", "Email": None, "Product": "Tablet", "Quantity": None, "Price": 600.00, "Purchase Date": "2024-09-18", "Delivery Status": False},
    {"Transaction ID": 1007, "Customer Name": "Grace Lee", "Email": "grace.lee@example.com", "Product": "Laptop", "Quantity": 1, "Price": 1200.00, "Purchase Date": "2024-09-19", "Delivery Status": True},
    {"Transaction ID": 1008, "Customer Name": "Hank Brown", "Email": "hank.brown@example.com", "Product": "Monitor", "Quantity": 2, "Price": 300.00, "Purchase Date": "09/19/2024", "Delivery Status": True},
    {"Transaction ID": 1009, "Customer Name": "Ivy Thompson", "Email": None, "Product": "Keyboard", "Quantity": 2, "Price": 100.00, "Purchase Date": "2024/09/20", "Delivery Status": False},
    {"Transaction ID": 1010, "Customer Name": "Jack Davis", "Email": "jack@example.com", "Product": "Mouse", "Quantity": 5, "Price": 50.00, "Purchase Date": "2024-09-21", "Delivery Status": True},
    {"Transaction ID": 1011, "Customer Name": "Alice Smith", "Email": "alice@example.com", "Product": "Laptop", "Quantity": 1, "Price": 1200.00, "Purchase Date": "2024-09-15", "Delivery Status": True},  # Duplicate entry
    {"Transaction ID": 1012, "Customer Name": "Kurt Evans", "Email": "kurt.evans@example.com", "Product": "Smartwatch", "Quantity": -1, "Price": 200.00, "Purchase Date": "2024-09-22", "Delivery Status": True},  # Outlier quantity
    {"Transaction ID": 1013, "Customer Name": "Liam Adams", "Email": "liam.adams@example.com", "Product": "Headphones", "Quantity": 2, "Price": 150.00, "Purchase Date": "2024-09-23", "Delivery Status": False},
    {"Transaction ID": 1014, "Customer Name": "Mia Clark", "Email": "mia.clark@example.com", "Product": None, "Quantity": 1, "Price": 0, "Purchase Date": "2024-09-24", "Delivery Status": True},  # Price anomaly
    {"Transaction ID": 1015, "Customer Name": "Nina Turner", "Email": None, "Product": "Tablet", "Quantity": 1, "Price": 600.00, "Purchase Date": "24-09-2024", "Delivery Status": True},
    {"Transaction ID": 1016, "Customer Name": "Oscar Harris", "Email": "oscar.harris@example.com", "Product": "Laptop", "Quantity": 2, "Price": 1200.00, "Purchase Date": "2024-09-25", "Delivery Status": True},
    {"Transaction ID": 1017, "Customer Name": "Paul Young", "Email": "paulyoung", "Product": "Monitor", "Quantity": 2, "Price": 300.00, "Purchase Date": "09/25/2024", "Delivery Status": True},
    {"Transaction ID": 1018, "Customer Name": "Quinn Lopez", "Email": None, "Product": "Smartphone", "Quantity": 1, "Price": 800.00, "Purchase Date": "2024-09-26", "Delivery Status": False},
    {"Transaction ID": 1019, "Customer Name": "Rachel Scott", "Email": "rachel.scott@example.com", "Product": "Keyboard", "Quantity": 2, "Price": 100.00, "Purchase Date": "2024-09-27", "Delivery Status": True},
    {"Transaction ID": 1020, "Customer Name": "Steve King", "Email": "steve.king@example.com", "Product": "Mouse", "Quantity": None, "Price": 50.00, "Purchase Date": "2024-09-28", "Delivery Status": True},
    {"Transaction ID": 1020, "Customer Name": "Steve King", "Email": "steve.king@example.com", "Product": "Mouse", "Quantity": None, "Price": 50.00, "Purchase Date": "2024-09-28", "Delivery Status": True},

]

<div style="background-color: rgba(40, 224, 224, 1); color: white ; padding: 4px;">
    <h3>Load it into DataFrame
</h3> </div>

In [3]:
df=pd.DataFrame(data)
df

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,None,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,1.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True
5,1006,Frank Wright,None,Tablet,NaN,600.0,2024-09-18,False
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,None,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,1014,Mia Clark,mia.clark@example.com,None,1.0,0.0,2024-09-24,True
14,1015,Nina Turner,None,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,None,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True
20,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

<div style="background-color: skyblue; color: white ; padding: 4px;">
    <h3>Data inspection
</h3> </div>

In [4]:
 #print top 15 
df.head()   #Viewing the First Few Records
df

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,None,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,1.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True
5,1006,Frank Wright,None,Tablet,NaN,600.0,2024-09-18,False
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,None,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,1014,Mia Clark,mia.clark@example.com,None,1.0,0.0,2024-09-24,True
14,1015,Nina Turner,None,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,None,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True
20,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

In [5]:
df.tail() #Viewing the last Few Records

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,None,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True
20,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

In [6]:
df.shape

(21, 8)

In [7]:
df.info

<bound method DataFrame.info of     Transaction ID    Customer Name                     Email     Product  \
0             1001      Alice Smith         alice@example.com      Laptop
1             1002        Bob Jones                      None  Headphones
2             1003  Charlie Johnson       charlie#example.com  Smartphone
3             1004        David Lee     david.lee@example.com      Laptop
4             1005     Eve Martinez  eve.martinez@example.com  Smartwatch
5             1006     Frank Wright                      None      Tablet
6             1007        Grace Lee     grace.lee@example.com      Laptop
7             1008       Hank Brown    hank.brown@example.com     Monitor
8             1009     Ivy Thompson                      None    Keyboard
9             1010       Jack Davis          jack@example.com       Mouse
10            1011      Alice Smith         alice@example.com      Laptop
11            1012       Kurt Evans    kurt.evans@example.com  Smartwatch
12            1013       Liam Adams    liam.adams@example.com  Headphones
13            1014        Mia Clark     mia.clark@example.com        None
14            1015      Nina Turner                      None      Tablet
15            1016     Oscar Harris  oscar.harris@example.com      Laptop
16            1017       Paul Young                 paulyoung     Monitor
17            1018      Quinn Lopez                      None  Smartphone
18            1019     Rachel Scott  rachel.scott@example.com    Keyboard
19            1020       Steve King    steve.king@example.com       Mouse
20            1020       Steve King    steve.king@example.com       Mouse

    Quantity   Price  Purchase Date  Delivery Status
0        1.0  1200.0     2024-09-15             True
1        2.0   150.0     2024-09-16             True
2        1.0   800.0     16/09/2024             True
3        1.0  1200.0     2024-09-17            False
4        3.0     NaN  17th Sep 2024             True
5        NaN   600.0     2024-09-18            False
6        1.0  1200.0     2024-09-19             True
7        2.0   300.0     09/19/2024             True
8        2.0   100.0     2024/09/20            False
9        5.0    50.0     2024-09-21             True
10       1.0  1200.0     2024-09-15             True
11      -1.0   200.0     2024-09-22             True
12       2.0   150.0     2024-09-23            False
13       1.0     0.0     2024-09-24             True
14       1.0   600.0     24-09-2024             True
15       2.0  1200.0     2024-09-25             True
16       2.0   300.0     09/25/2024             True
17       1.0   800.0     2024-09-26            False
18       2.0   100.0     2024-09-27             True
19       NaN    50.0     2024-09-28             True
20       NaN    50.0     2024-09-28             True  >

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Transaction ID   21 non-null     int64
 1   Customer Name    21 non-null     object
 2   Email            16 non-null     object
 3   Product          20 non-null     object
 4   Quantity         18 non-null     float64
 5   Price            20 non-null     float64
 6   Purchase Date    21 non-null     object
 7   Delivery Status  21 non-null     bool
dtypes: bool(1), float64(2), int64(1), object(4)
memory usage: 1.3+ KB

In [9]:
df.columns

Index(['Transaction ID', 'Customer Name', 'Email', 'Product', 'Quantity',
       'Price', 'Purchase Date', 'Delivery Status'],
      dtype='object')

In [10]:
df.describe() #statistical Summary of the Dataset

       Transaction ID   Quantity        Price
count       21.000000  18.000000    20.000000
mean      1010.952381   1.611111   512.500000
std          6.127611   1.195033   472.361091
min       1001.000000  -1.000000     0.000000
25%       1006.000000   1.000000   100.000000
50%       1011.000000   1.500000   300.000000
75%       1016.000000   2.000000   900.000000
max       1020.000000   5.000000  1200.000000

In [11]:
df.describe

<bound method NDFrame.describe of     Transaction ID    Customer Name                     Email     Product  \
0             1001      Alice Smith         alice@example.com      Laptop
1             1002        Bob Jones                      None  Headphones
2             1003  Charlie Johnson       charlie#example.com  Smartphone
3             1004        David Lee     david.lee@example.com      Laptop
4             1005     Eve Martinez  eve.martinez@example.com  Smartwatch
5             1006     Frank Wright                      None      Tablet
6             1007        Grace Lee     grace.lee@example.com      Laptop
7             1008       Hank Brown    hank.brown@example.com     Monitor
8             1009     Ivy Thompson                      None    Keyboard
9             1010       Jack Davis          jack@example.com       Mouse
10            1011      Alice Smith         alice@example.com      Laptop
11            1012       Kurt Evans    kurt.evans@example.com  Smartwatch
12            1013       Liam Adams    liam.adams@example.com  Headphones
13            1014        Mia Clark     mia.clark@example.com        None
14            1015      Nina Turner                      None      Tablet
15            1016     Oscar Harris  oscar.harris@example.com      Laptop
16            1017       Paul Young                 paulyoung     Monitor
17            1018      Quinn Lopez                      None  Smartphone
18            1019     Rachel Scott  rachel.scott@example.com    Keyboard
19            1020       Steve King    steve.king@example.com       Mouse
20            1020       Steve King    steve.king@example.com       Mouse

    Quantity   Price  Purchase Date  Delivery Status
0        1.0  1200.0     2024-09-15             True
1        2.0   150.0     2024-09-16             True
2        1.0   800.0     16/09/2024             True
3        1.0  1200.0     2024-09-17            False
4        3.0     NaN  17th Sep 2024             True
5        NaN   600.0     2024-09-18            False
6        1.0  1200.0     2024-09-19             True
7        2.0   300.0     09/19/2024             True
8        2.0   100.0     2024/09/20            False
9        5.0    50.0     2024-09-21             True
10       1.0  1200.0     2024-09-15             True
11      -1.0   200.0     2024-09-22             True
12       2.0   150.0     2024-09-23            False
13       1.0     0.0     2024-09-24             True
14       1.0   600.0     24-09-2024             True
15       2.0  1200.0     2024-09-25             True
16       2.0   300.0     09/25/2024             True
17       1.0   800.0     2024-09-26            False
18       2.0   100.0     2024-09-27             True
19       NaN    50.0     2024-09-28             True
20       NaN    50.0     2024-09-28             True  >

In [12]:
df.describe(include='all')

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
count,21.000000,21,16,20,18.000000,20.000000,21,21
unique,NaN,19,14,8,NaN,NaN,19,2
top,NaN,Alice Smith,alice@example.com,Laptop,NaN,NaN,2024-09-15,True
freq,NaN,2,2,5,NaN,NaN,2,16
mean,1010.952381,NaN,NaN,NaN,1.611111,512.500000,NaN,NaN
std,6.127611,NaN,NaN,NaN,1.195033,472.361091,NaN,NaN
min,1001.000000,NaN,NaN,NaN,-1.000000,0.000000,NaN,NaN
25%,1006.000000,NaN,NaN,NaN,1.000000,100.000000,NaN,NaN
50%,1011.000000,NaN,NaN,NaN,1.500000,300.000000,NaN,NaN
75%,1016.000000,NaN,NaN,NaN,2.000000,900.000000,NaN,NaN
max,1020.000000,NaN,NaN,NaN,5.000000,1200.000000,NaN,NaN

In [13]:
df.sample(6)  #random Sampling from the Data

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
8,1009,Ivy Thompson,None,Keyboard,2.0,100.0,2024/09/20,False
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
20,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True
1,1002,Bob Jones,None,Headphones,2.0,150.0,2024-09-16,True

In [14]:
df['Customer Name'].unique()

array(['Alice Smith', 'Bob Jones', 'Charlie Johnson', 'David Lee',
       'Eve Martinez', 'Frank Wright', 'Grace Lee', 'Hank Brown',
       'Ivy Thompson', 'Jack Davis', 'Kurt Evans', 'Liam Adams',
       'Mia Clark', 'Nina Turner', 'Oscar Harris', 'Paul Young',
       'Quinn Lopez', 'Rachel Scott', 'Steve King'], dtype=object)

In [15]:

df['Customer Name'].head()

0        Alice Smith
1          Bob Jones
2    Charlie Johnson
3          David Lee
4       Eve Martinez
Name: Customer Name, dtype: object

<div style="background-color: skyblue; color: white ; padding: 4px;">
    <h3>Handling missing data
</h3> </div>

## **Identification:**  Use df.isnull().sum() to count missing values per column.

In [16]:
df.isnull().sum()  # Check missing values

Transaction ID     0
Customer Name      0
Email              5
Product            1
Quantity           3
Price              1
Purchase Date      0
Delivery Status    0
dtype: int64

## **Deletion:** Remove rows or columns with a high percentage of missing values using dropna().

In [17]:
df.dropna()  # Remove rows with missing data

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,1.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True

## **Imputation:** Fill missing values using methods like fillna() with a specified value (e.g., mean, median, mode) or a forward/backward fill.

In [18]:
df.fillna(0)      # Replace missing values with 0

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,0,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,1.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,0.0,17th Sep 2024,True
5,1006,Frank Wright,0,Tablet,0.0,600.0,2024-09-18,False
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,0,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,1014,Mia Clark,mia.clark@example.com,0,1.0,0.0,2024-09-24,True
14,1015,Nina Turner,0,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,0,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,0.0,50.0,2024-09-28,True
20,1020,Steve King,steve.king@example.com,Mouse,0.0,50.0,2024-09-28,True

<div style="background-color: skyblue; color: white ; padding: 4px;">
    <h3>Data cleaning
</h3> </div>

In [19]:
df.duplicated().sum()   # Check for  sum of duplicates

np.int64(1)

In [20]:
df[df.duplicated()] #seeing duplicate value

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
20,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

In [21]:
df.drop_duplicates()   # Remove duplicates

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,None,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,1.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True
5,1006,Frank Wright,None,Tablet,NaN,600.0,2024-09-18,False
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,None,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,1014,Mia Clark,mia.clark@example.com,None,1.0,0.0,2024-09-24,True
14,1015,Nina Turner,None,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,None,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

In [22]:

df_listwise_deletion=df.dropna()
df_listwise_deletion

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,1.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True

In [23]:
df_listwise_deletion.shape

(12, 8)

In [24]:

df_pairwise_deletion=df.dropna(subset=['Quantity']) #pair wise deletion

In [25]:

df_pairwise_deletion

,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,None,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,1.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,None,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,1014,Mia Clark,mia.clark@example.com,None,1.0,0.0,2024-09-24,True
14,1015,Nina Turner,None,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,None,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True

In [26]:

df.isnull().sum()

Transaction ID     0
Customer Name      0
Email              5
Product            1
Quantity           3
Price              1
Purchase Date      0
Delivery Status    0
dtype: int64

In [27]:
df_pairwise_deletion.isnull().sum()

Transaction ID     0
Customer Name      0
Email              4
Product            1
Quantity           0
Price              1
Purchase Date      0
Delivery Status    0
dtype: int64

In [28]:

df_pairwise_deletion.shape

(18, 8)

In [29]:

df.rename(columns={'Price':"Cost"})

,Transaction ID,Customer Name,Email,Product,Quantity,Cost,Purchase Date,Delivery Status
0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1002,Bob Jones,None,Headphones,2.0,150.0,2024-09-16,True
2,1003,Charlie Johnson,charlie#example.com,Smartphone,1.0,800.0,16/09/2024,True
3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True
5,1006,Frank Wright,None,Tablet,NaN,600.0,2024-09-18,False
6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,1009,Ivy Thompson,None,Keyboard,2.0,100.0,2024/09/20,False
9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True
10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,1014,Mia Clark,mia.clark@example.com,None,1.0,0.0,2024-09-24,True
14,1015,Nina Turner,None,Tablet,1.0,600.0,24-09-2024,True
15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,1018,Quinn Lopez,None,Smartphone,1.0,800.0,2024-09-26,False
18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True
20,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

In [30]:

df.reset_index()

,index,Transaction ID,Customer Name,Email,Product,Quantity,Price,Purchase Date,Delivery Status
0,0,1001,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
1,1,1002,Bob Jones,None,Headphones,2.0,150.0,2024-09-16,True
2,2,1003,Charlie Johnson,charlie#example.com,Smartphone,1.0,800.0,16/09/2024,True
3,3,1004,David Lee,david.lee@example.com,Laptop,1.0,1200.0,2024-09-17,False
4,4,1005,Eve Martinez,eve.martinez@example.com,Smartwatch,3.0,NaN,17th Sep 2024,True
5,5,1006,Frank Wright,None,Tablet,NaN,600.0,2024-09-18,False
6,6,1007,Grace Lee,grace.lee@example.com,Laptop,1.0,1200.0,2024-09-19,True
7,7,1008,Hank Brown,hank.brown@example.com,Monitor,2.0,300.0,09/19/2024,True
8,8,1009,Ivy Thompson,None,Keyboard,2.0,100.0,2024/09/20,False
9,9,1010,Jack Davis,jack@example.com,Mouse,5.0,50.0,2024-09-21,True
10,10,1011,Alice Smith,alice@example.com,Laptop,1.0,1200.0,2024-09-15,True
11,11,1012,Kurt Evans,kurt.evans@example.com,Smartwatch,-1.0,200.0,2024-09-22,True
12,12,1013,Liam Adams,liam.adams@example.com,Headphones,2.0,150.0,2024-09-23,False
13,13,1014,Mia Clark,mia.clark@example.com,None,1.0,0.0,2024-09-24,True
14,14,1015,Nina Turner,None,Tablet,1.0,600.0,24-09-2024,True
15,15,1016,Oscar Harris,oscar.harris@example.com,Laptop,2.0,1200.0,2024-09-25,True
16,16,1017,Paul Young,paulyoung,Monitor,2.0,300.0,09/25/2024,True
17,17,1018,Quinn Lopez,None,Smartphone,1.0,800.0,2024-09-26,False
18,18,1019,Rachel Scott,rachel.scott@example.com,Keyboard,2.0,100.0,2024-09-27,True
19,19,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True
20,20,1020,Steve King,steve.king@example.com,Mouse,NaN,50.0,2024-09-28,True

<div style="background-color: #01377D; padding: 10px; text-align: center; color: white; font-size: 32px; font-family: 'Arial', sans-serif;">
    End <br><br>
    
</div>