<div style="background-color:#009DD1; padding: 10px; height: 70px; border-radius: 15px;">
    <div style="font-family: 'Georgia', serif; font-size: 20px;color: white; padding: 10px; text-align: right; position: absolute; right: 20px;">
        Sakshi <br>
        <span style="font-family: 'Arial', sans-serif;font-size: 14px; color: white">Data Analytics Trainee|AI/ML bootcamp</span> 
    </div>
</div>

<div style="background-color: #01377D; padding: 10px; text-align: center; color: white; font-size: 32px; font-family: 'Arial', sans-serif;">
    Data Cleaning & Visualization <br><br>
    
</div>

<div style="background-color: #97E7F5; color: white ; padding: 4px;">
    <h3>Import Libraries
</h3> </div>

In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

<div style="background-color: #9F149F; color: white ; padding: 4px;">
    <h3>step 1. create synthetic healthcare data
</h3> </div>

In [2]:
#Create synthesis healthcare data and loading it 


data={
    "patient_id": [1,2,3,4,5,6,7,8],
    "name":["AB","BC","CD","DE","EF","GH","IJ","KL"],
    "age":[34,np.nan,45,29,50,62,np.nan,34],
    "gender":["M","F","M","F","M","F","M","F"],
    "blood_pressure":["120/80",None,"140/90","abc","130/85","150/85","120/80",None],
    "diagnosis":["Hypertension","Diabetes","hypertension","HYPERTENSION","Pre-diabetes","diabetes","None","Pre-diabetes"],
    "data_of_visit":["2023-01-10","2023-02-19","15/02/2023","2023-05-23","2023-02-09","invalid_date","18/02/2023","10/04/2024"]
}

<div style="background-color: #9F149F; color: white ; padding: 4px;">
    <h3>step 2: Load it into DataFrame
</h3> </div>

In [4]:
df = pd.DataFrame(data)

In [5]:
df

   patient_id name   age gender blood_pressure     diagnosis data_of_visit
0           1   AB  34.0      M         120/80  Hypertension    2023-01-10
1           2   BC   NaN      F           None      Diabetes    2023-02-19
2           3   CD  45.0      M         140/90  hypertension    15/02/2023
3           4   DE  29.0      F            abc  HYPERTENSION    2023-05-23
4           5   EF  50.0      M         130/85  Pre-diabetes    2023-02-09
5           6   GH  62.0      F         150/85      diabetes  invalid_date
6           7   IJ   NaN      M         120/80          None    18/02/2023
7           8   KL  34.0      F           None  Pre-diabetes    10/04/2024

<div style="background-color: #9F149F; color: white ; padding: 4px;">
    <h3>step 3: Perform data cleaning
</h3> </div>

## Normalize Diagnosis

In [6]:
df['diagnosis']=df['diagnosis'].str.lower().str.strip()
df

   patient_id name   age gender blood_pressure     diagnosis data_of_visit
0           1   AB  34.0      M         120/80  hypertension    2023-01-10
1           2   BC   NaN      F           None      diabetes    2023-02-19
2           3   CD  45.0      M         140/90  hypertension    15/02/2023
3           4   DE  29.0      F            abc  hypertension    2023-05-23
4           5   EF  50.0      M         130/85  pre-diabetes    2023-02-09
5           6   GH  62.0      F         150/85      diabetes  invalid_date
6           7   IJ   NaN      M         120/80          none    18/02/2023
7           8   KL  34.0      F           None  pre-diabetes    10/04/2024

## Replacing invalid / none values

In [8]:
df['diagnosis'].replace(["none","null",""],np.nan,inplace=True)
df

   patient_id name   age gender blood_pressure     diagnosis data_of_visit
0           1   AB  34.0      M         120/80  hypertension    2023-01-10
1           2   BC   NaN      F           None      diabetes    2023-02-19
2           3   CD  45.0      M         140/90  hypertension    15/02/2023
3           4   DE  29.0      F            abc  hypertension    2023-05-23
4           5   EF  50.0      M         130/85  pre-diabetes    2023-02-09
5           6   GH  62.0      F         150/85      diabetes  invalid_date
6           7   IJ   NaN      M         120/80           NaN    18/02/2023
7           8   KL  34.0      F           None  pre-diabetes    10/04/2024

## ImputIng missing ages

In [10]:
df['age']=df['age'].fillna(df['age'].median())

In [11]:
df

   patient_id name   age gender blood_pressure     diagnosis data_of_visit
0           1   AB  34.0      M         120/80  hypertension    2023-01-10
1           2   BC  39.5      F           None      diabetes    2023-02-19
2           3   CD  45.0      M         140/90  hypertension    15/02/2023
3           4   DE  29.0      F            abc  hypertension    2023-05-23
4           5   EF  50.0      M         130/85  pre-diabetes    2023-02-09
5           6   GH  62.0      F         150/85      diabetes  invalid_date
6           7   IJ  39.5      M         120/80           NaN    18/02/2023
7           8   KL  34.0      F           None  pre-diabetes    10/04/2024

## Clean Blood Pressure

In [10]:
df['blood_pressure']=df['blood_pressure'].where(df['blood_pressure'].str.contains(r'^\d+/\d+$'))
df

   patient_id name   age gender blood_pressure     diagnosis data_of_visit
0           1   AB  34.0      M         120/80  hypertension    2023-01-10
1           2   BC  39.5      F            NaN      diabetes    2023-02-19
2           3   CD  45.0      M         140/90  hypertension    15/02/2023
3           4   DE  29.0      F            NaN  hypertension    2023-05-23
4           5   EF  50.0      M         130/85  pre-diabetes    2023-02-09
5           6   GH  62.0      F         150/85      diabetes  invalid_date
6           7   IJ  39.5      M         120/80           NaN    18/02/2023
7           8   KL  34.0      F            NaN  pre-diabetes    10/04/2024

 ## r'^\d+/\d+$' -> regex pattern

  - ^( start of string)
  - \d (one or more digits)
  - / ( a forward slash)
  - \d ( one or more digits)
  - $ ( marks end of the string)

## Parse dates

In [12]:
df['data_of_visit']= pd.to_datetime(df['data_of_visit'], errors='coerce')
df

   patient_id name   age gender blood_pressure     diagnosis data_of_visit
0           1   AB  34.0      M         120/80  hypertension    2023-01-10
1           2   BC  39.5      F           None      diabetes    2023-02-19
2           3   CD  45.0      M         140/90  hypertension           NaT
3           4   DE  29.0      F            abc  hypertension    2023-05-23
4           5   EF  50.0      M         130/85  pre-diabetes    2023-02-09
5           6   GH  62.0      F         150/85      diabetes           NaT
6           7   IJ  39.5      M         120/80           NaN           NaT
7           8   KL  34.0      F           None  pre-diabetes           NaT

coerce (not a time)

# Extract duplicate values

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df

   patient_id name   age gender blood_pressure     diagnosis data_of_visit
0           1   AB  34.0      M         120/80  hypertension    2023-01-10
1           2   BC  39.5      F           None      diabetes    2023-02-19
2           3   CD  45.0      M         140/90  hypertension           NaT
3           4   DE  29.0      F            abc  hypertension    2023-05-23
4           5   EF  50.0      M         130/85  pre-diabetes    2023-02-09
5           6   GH  62.0      F         150/85      diabetes           NaT
6           7   IJ  39.5      M         120/80           NaN           NaT
7           8   KL  34.0      F           None  pre-diabetes           NaT

## deleting NaN

In [16]:
df.dropna(subset=['diagnosis','data_of_visit'],inplace=True)
df

   patient_id name   age gender blood_pressure     diagnosis data_of_visit
0           1   AB  34.0      M         120/80  hypertension    2023-01-10
1           2   BC  39.5      F           None      diabetes    2023-02-19
3           4   DE  29.0      F            abc  hypertension    2023-05-23
4           5   EF  50.0      M         130/85  pre-diabetes    2023-02-09

In [17]:
df.dropna(subset=['blood_pressure'],inplace=True)
df

   patient_id name   age gender blood_pressure     diagnosis data_of_visit
0           1   AB  34.0      M         120/80  hypertension    2023-01-10
3           4   DE  29.0      F            abc  hypertension    2023-05-23
4           5   EF  50.0      M         130/85  pre-diabetes    2023-02-09

In [16]:
# read_csv